ANNOTATE = yes
SOURCES = geohash_ext.ml b32.ml geohash.mli geohash.ml 
RESULT = geohash
LIBINSTALL_FILES = META geohash.cma geohash.cmxa geohash.a geohash.cmi
PACKS = extlib

.PHONY: all
all: ncl dcl
	@ :

OCAMLMAKEFILE=../OCamlMakefile
include $(OCAMLMAKEFILE)