OCAMLMAKEFILE=../OCamlMakefile

ANNOTATE = yes
SOURCES = geohash.ml
RESULT = geohash
LIBINSTALL_FILES = META geohash.cma geohash.cmxa geohash.a geohash.cmi
PACKS = extlib
#FLAGS = -thread

.PHONY: all
all: ncl dcl
	@ :

include $(OCAMLMAKEFILE)